
# Usage:
# Route Access Type > Route > Route Config
#
# HTTP Route allows the following config:
# - path : The relative path to this route. Mandatory config.
# - method : Restrict path access to the given HTTP method.
# - controller : The controller to use to process this route
# - restrictTo : Restriction configuration for this route, you can customize accessibility, the common field is "role".
# - render : The template to render this route, using StaticPageController. Processed as option.
# Other fields will be send as options to the controller, controller can access to all this configuration.
#
# Roles: visitor, member, moderator, administrator, developer
# Unspecified role does not restrict access, "visitor" restricts to not-logged user only.

http:
    
    # Resources
    
    resources_orpheus_test:
        path: "/res/orpheus-test/{path:resource}"
        controller: "Orpheus\\Controller\\ResourceController"
        package: "orpheus/orpheus-test"
